from selenium.webdriver.common.by import By


class Selectors_List:
    ERROR_MESSAGE = (By.XPATH, '//h3[@data-test="error"]')
    FIRST_NAME = (By.ID, 'first-name')
    LAST_NAME = (By.ID, 'last-name')
    POSTAL_CODE = (By.ID, 'postal-code')
    LOGIN_BUTTON = (By.ID, "login-button")
    USER_NAME = (By.ID, "user-name")
    PASSWORD = (By.ID, "password")
    PRODUCT_SORT_CONTAINER = (By.XPATH, '//*[@class= "product_sort_container"]')
    INVENTORY_ITEM_PRICE = (By.XPATH, '//*[@class = "inventory_item_price"]')
    INVENTORY_ITEM_NAME = (By.XPATH, '//*[@class = "inventory_item_name"]')
    ADD_TO_CART_BTN = (By.ID, 'add-to-cart-sauce-labs-backpack')
    SHOPPING_CART_CONTAINER = (By.CLASS_NAME, 'shopping_cart_link')
    REMOVE_SAUCE_LABS_BACKPACK_BTN_INPUT = (By.XPATH, '//button[@class="btn btn_secondary btn_small btn_inventory')
    SWAG_LABS_LOGO = (By.XPATH, '//*[@class = "app_logo"]')
    CHECKOUT_BTN = (By.ID, 'checkout')
    CONTINUE_BTN = (By.ID, 'continue')
    FINISH_BTN = (By.ID, 'finish')
    ORDER_COMPLETE_MESSAGE = (By.XPATH, '//div[@id="checkout_complete_container"]//h2')
    REMOVE_PRODUCT = (By.ID, 'remove-sauce-labs-backpack')
    CONTINUE_SHOPPING_BTN = (By.ID, 'continue-shopping')
    CANCEL_BTN = (By.ID, 'cancel')
    BACK_TO_PRODUCTS = (By.ID, 'back-to-products')